import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const packageJsonPath = join(packageRoot, "package.json");
const generatedPath = join(packageRoot, "src", "version.generated.ts");

const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8"));
assert.equal(typeof packageJson.version, "string");
assert.match(packageJson.version, /^\d+\.\d+\.\d+/);

const contents = `/* Generated by scripts/generate-version.mjs — do not edit. */
export const EXTENSION_VERSION = ${JSON.stringify(packageJson.version)} as const;
`;

const mode = process.argv.includes("--check") ? "check" : "write";

if (mode === "check") {
	let existing = "";
	try {
		existing = readFileSync(generatedPath, "utf8");
	} catch {
		console.error(`Missing ${generatedPath}. Run: node scripts/generate-version.mjs`);
		process.exit(1);
	}
	if (existing !== contents) {
		console.error(
			`Version drift: ${generatedPath} does not match package.json (${packageJson.version}).`,
		);
		process.exit(1);
	}
	console.log(`check:version ok (${packageJson.version})`);
	process.exit(0);
}

writeFileSync(generatedPath, contents);
console.log(`Wrote ${generatedPath} (${packageJson.version})`);
